name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Lint
        run: pnpm run lint

      - name: Run test
        run: pnpm --filter timescape -- test run --coverage.enabled=true --coverage.reporter=text

      - name: Install Playwright Browsers
        run: pnpm --filter demo -- exec playwright install --with-deps

      - name: Run smoke tests
        run: pnpm --filter demo -- test
