name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Lint
        run: pnpm run lint

      - name: Run test
        run: pnpm --filter timescape -- test run --coverage.enabled=true --coverage.reporter=text
